eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

# Shared JWT Secret
jwt:
  secret: "agms-super-secret-key-32-characters-long-12345"
  expiration: 86400000 # 24 hours
