spring:
  datasource:
    url: jdbc:mysql://localhost:3306/sensor_db
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: update

iot:
  api:
    base-url: http://104.211.95.241:8080
    username: your-registered-email
    password: your-password
    device-id: your-device-id