server:
  port: 8082

spring:
  application:
    name: sensor-service

  datasource:
    url: jdbc:h2:mem:sensor_db
    driver-class-name: org.h2.Driver
    username: sa
    password: ""

  h2:
    console:
      enabled: true
      path: /h2-console

  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: update
    show-sql: true

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/

iot:
  api:
    base-url: http://104.211.95.241:8080/api
  credentials:
    username: student123
    password: password123