spring:
  cloud:
    gateway:
      routes:
        - id: zone-service
          uri: lb://zone-service
          predicates:
            - Path=/api/zones/**
        - id: sensor-service
          uri: lb://sensor-service
          predicates:
            - Path=/api/sensors/**
        - id: automation-service
          uri: lb://automation-service
          predicates:
            - Path=/api/automation/**
        - id: crop-service
          uri: lb://crop-service
          predicates:
            - Path=/api/crops/**

jwt:
  secret: dGhpcy1pcy1hLXNlY3VyZS1iYXNlNjQtMzItYnl0ZXMtc2VjcmV0
  expiration: 86400000